
compatibility_date = "2024-01-01"
main = "dist/cloudflare-workers-bundle/index.js"
name = "hattip-basic"
usage_model = 'bundled'
workers_dev = true

[site]
bucket = "./public"

[build]
command = "npm run build:cfw"
